interface TiktokParams {
  content_type?: 'product' | 'product_group';
  content_id?: string;
  contents?: ContentParams[];
  content_category?: string;
  content_name?: string;
  currency?:
    | 'AED'
    | 'ARS'
    | 'AUD'
    | 'BDT'
    | 'BHD'
    | 'BIF'
    | 'BOB'
    | 'BRL'
    | 'CAD'
    | 'CHF'
    | 'CLP'
    | 'CNY'
    | 'COP'
    | 'CRC'
    | 'CZK'
    | 'DKK'
    | 'DZD'
    | 'EGP'
    | 'EUR'
    | 'GBP'
    | 'GTQ'
    | 'HKD'
    | 'HNL'
    | 'HUF'
    | 'IDR'
    | 'ILS'
    | 'INR'
    | 'ISK'
    | 'JPY'
    | 'KES'
    | 'KHR'
    | 'KRW'
    | 'KWD'
    | 'KZT'
    | 'MAD'
    | 'MOP'
    | 'MXN'
    | 'MYR'
    | 'NGN'
    | 'NIO'
    | 'NOK'
    | 'NZD'
    | 'OMR'
    | 'PEN'
    | 'PHP'
    | 'PHP'
    | 'PKR'
    | 'PLN'
    | 'PYG'
    | 'QAR'
    | 'RON'
    | 'RUB'
    | 'SAR'
    | 'SEK'
    | 'SGD'
    | 'THB'
    | 'TRY'
    | 'TWD'
    | 'UAH'
    | 'USD'
    | 'VES'
    | 'VND'
    | 'ZAR';
  value?: number;
  price?: number;
  quantity?: number;
  query?: string;
  description?: string;
  status?: string;
}

interface ContentParams {
  content_id?: string;
  content_type?: string;
  content_name?: string;
  quantity: number;
  price: number;
}
